# Generated by Django 3.1 on 2020-08-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Movie',
        ),
    ]
