# Generated by Django 3.1 on 2020-08-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published_date']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='dislike',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='like',
            new_name='score_sum',
        ),
    ]
