# Generated by Django 3.1 on 2020-08-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_auto_20200819_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie', unique=True),
        ),
    ]
