# Generated by Django 3.1 on 2020-08-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_auto_20200819_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='score',
            new_name='comment_score',
        ),
    ]
