# Generated by Django 3.1 on 2020-08-19 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0013_auto_20200819_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes_user',
            field=models.ManyToManyField(blank=True, related_name='likes_user', through='movieapp.WishList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
